### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by sunxm19** [cmartin/ggConvexHull#1]
I get these error when using `devtools::install_github("cmartin/ggConvexHull")` to download: 
 `Error: Failed to install 'ggConvexHull' from GitHub:
  Does not appear to be an R package (no DESCRIPTION)
In addition: Warning messages:
1: In utils::untar(tarfile, ...) :
  ‘tar.exe -xf "C:\Temp\RtmpuG4U8Y\file4843cb1555e.tar.gz" -C "C:/Temp/RtmpuG4U8Y/remotes4846d096ca1"’ returned error code 1
2: In system(cmd, intern = TRUE) :
  running command 'tar.exe -tf "C:\Temp\RtmpuG4U8Y\file4843cb1555e.tar.gz"' had status 1`

**Comment by cmartin** [comment]
Sorry. I could not reproduce the error on my end. The package installed correctly this morning on a clean environment.

Can you install other packages from github successfully?
